{% set version = "2.5.4" %}
{% set libltdl_version = "2.4.3a" %}

package:
  name: libtool-split
  version: {{ version }}

source:
  url: http://ftpmirror.gnu.org/libtool/libtool-{{ version }}.tar.gz
  sha256: da8ebb2ce4dcf46b90098daf962cffa68f4b4f62ea60f798d0ef12929ede6adf
  patches:
    # From: https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=557388;filename=link-as-needed.patch;msg=5
    # See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=347650
    # and: https://sigquit.wordpress.com/2011/02/16/why-asneeded-doesnt-work-as-expected-for-your-libraries-on-your-autotools-project/
    - patches/0001-link-as-needed.patch
    - patches/0002-apple-silicon.patch

build:
  number: 0
  skip: true  # [win]
  ignore_run_exports_from:
    - {{ compiler('cxx') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - m4
    - help2man
    - autoconf
    - automake
    - make
    - patch

outputs:
  - name: libtool
    script: build_libtool.sh
    build:
      ignore_run_exports_from:
      - {{ compiler('cxx') }}
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - m4
        - help2man
        - autoconf
        - automake
        - make
        - texinfo
        - patch
      host:
        - {{ pin_subpackage('libltdl', exact=true) }}
      run:
        - {{ pin_subpackage('libltdl', exact=true) }}
    test:
      commands: $RECIPE_DIR/parent/run_test_libtool.sh
      requires:
        - {{ compiler('cxx') }}
    about:
      license: GPL-2.0-or-later AND LGPL-2.0-or-later
      license_file:
        - COPYING
        - libltdl/COPYING.LIB
  - name: libltdl
    version: {{ libltdl_version }}
    script: build_libltdl.sh
    build:
      ignore_run_exports_from:
      - {{ compiler('cxx') }}
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - m4
        - help2man
        - autoconf
        - automake
        - make
        - texinfo
        - patch
      about:
        license: LGPL-2.0-or-later
        license_file: libltdl/COPYING.LIB

about:
  home: http://www.gnu.org/software/libtool/
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: The GNU Portable Library Tool
  description: |
    GNU libtool is a generic library support script. Libtool hides the
    complexity of using shared libraries behind a consistent, portable
    interface.
  doc_url: http://www.gnu.org/software/libtool/manual/
  dev_url: http://git.savannah.gnu.org/cgit/libtool.git

extra:
  recipe-maintainers:
    - ocefpaf
    - msarahan
    - jakirkham
    - mingwandroid
    - isuruf
    - saraedum
